apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitbucket-deployment
  labels:
    app: bitbucket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitbucket
  template:
    metadata:
      labels:
        app: bitbucket
    spec:
      containers:
      - name: bitbucket
        image: atlassian/bitbucket-server
        ports:
        - containerPort: 7990
          name: bitbucket-http
        - containerPort: 22
          name: bitbucket-ssh
        volumeMounts:
        - mountPath: /var/atlassian/application-data/bitbucket
          name: bitbucket-data
        env:
        - name: SERVER_SECURE
          value: "true"
        - name: SERVER_SCHEME
          value: "https"
        - name: SERVER_PROXY_PORT
          value: "443"
        - name: SERVER_PROXY_NAME
          value: ""
      volumes:
        - name: bitbucket-data
          persistentVolumeClaim:
            claimName: bitbucket-pv-claim
