apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: bitbucket-postgres
                key: postgres_db
          - name: POSTGRES_ADMIN
            valueFrom:
              secretKeyRef:
                name: bitbucket-postgres
                key: username
          - name: POSTGRES_PW
            valueFrom:
              secretKeyRef:
                name: bitbucket-postgres
                key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
