kind: PersistentVolume
apiVersion: v1
metadata:
  name: bitbucket-pv-volume
  labels:
    type: local
    app: bitbucket
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kube-data/bitbucket"
    type: Directory
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bitbucket-pv-claim
  labels:
    app: bitbucket
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
