apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: devops 
  name: jenkins-pvc
  labels:
    app: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
