apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: deploy
  name: nexus-pvc
  labels:
    app: nexus 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
