apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  type: LoadBalancer
  ports:
  - name: mariadb
    port: 3306
  selector:
    app: mariadb
---
# Headless service for stable DNS entries of StatefulSet members.
# For writes, you must instead connect to the master: mysql-0.mysql.
apiVersion: v1
kind: Service
metadata:
  name: mariadb-write
  labels:
    app: mariadb
spec:
  ports:
  - name: mariadb
    port: 3306
  clusterIP: None
  selector:
    app: mariadb
