apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb
  labels:
    app: mariadb
data:
  master.cnf: |
    # Apply this config only on the master.
    [mysqld]
    log-bin
    log-basename=master
  slave.cnf: |
    # Apply this config only on slaves.
    [mysqld]
    read-only
    log-bin
    log-basename=master
    report-host=slave
