apiVersion: extensions/v1beta1 
kind: Deployment 
metadata: 
  name: deploy-test
  namespace: default
spec: 
  replicas: 1 
  template: 
    metadata: 
      labels: 
        app: deploy-test
    spec: 
      containers: 
      - name: deploy-test
        image: asia.gcr.io/metaportal/deploy-test:latest
        ports: 
        - containerPort: 8080 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: deploy-test-svc
  namespace: default 
  labels: 
    app: deploy-test 
spec: 
  type: LoadBalancer
  ports: 
  - port: 80
    targetPort: 8080 
    protocol: TCP 
    name: http 
  selector: 
    app: deploy-test
