# Headless service for galera statefulset
---
apiVersion: v1
kind: Service
metadata:
  namespace: metaportal
  name: mariadb
  labels:
    app: mariadb
spec:
  ports:
  - port: 3306
    name: mariadb
  clusterIP: None
  selector:
    app: mariadb 

---

# Client service for connecting to any MySQL instance for reads.
# For writes, you must instead connect to the master: galera-ss-0.galera-hs.
apiVersion: v1
kind: Service
metadata:
  namespace: metaportal
  name: mariadb-client
  labels:
    app: mariadb
spec:
  type: LoadBalancer
  ports:
  - port: 3306
    name: mariadb
  selector:
    app: mariadb

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: metaportal
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: "galera-hs"
  replicas: 3
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: galera
        image: asia.gcr.io/metaportal/mariadb:10.1
        #image: drlee001/mariadb:10.1-modcnf
        ports:
        - name: mysql
          containerPort: 3306
        env:
        # kubectl create secret generic mysql-pass --from-file=password.txt
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-pass
              key: password
        - name: DISCOVERY_SERVICE
          value: etcd-client:2379
        - name: XTRABACKUP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-pass
              key: xtrapassword
        - name: CLUSTER_NAME
          value: mariadb_galera_ss
        - name: MYSQL_DATABASE
          value: metaportal
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-pass
              key: id
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-pass
              key: pass
        readinessProbe:
          exec:
            command:
            - /healthcheck.sh
            - --readiness
          initialDelaySeconds: 120
          periodSeconds: 1
        livenessProbe:
          exec:
            command:
            - /healthcheck.sh
            - --liveness
          initialDelaySeconds: 120
          periodSeconds: 1
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      namespace: metaportal
      name: mariadb-data
      #annotations:
        #volume.beta.kubernetes.io/storage-class: glusterfs-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
          #storage: 200Mi
